### ISSUE TITLE
"fetch" not defined when using Jest tests

### ISSUE THREAD

**Issue by Pet3ris** [reasonml-community/rescript-apollo-client#106]
Hi There,

I'm using a client (non-react/non-hook) query to run tests in jest and got the following error:

```
Invariant Violation: 
    "fetch" has not been found globally and no fetcher has been configured.
```

I saw that Apollo in javascript has an argument to directly pass the `fetch` function:

- https://stackoverflow.com/questions/50688998/using-apolloclient-with-node-js-fetch-is-not-found-globally-and-no-fetcher-pas
- https://github.com/apollographql/apollo-client/issues/4892

The same argument doesn't seem to exist as a `make()` argument for `ApolloClient`.

```rescript
let instance = {
  open ApolloClient
  make(
    ~cache=Cache.InMemoryCache.make(),
    ~connectToDevTools=false,
    ~uri=_ => graphql_api_address ++ "/graphql"
    // should fetch argument be supported here?
    (),
  )
}
```

Is there a workaround to be able to use Apollo in jest tests?

**Comment by jeddeloh** [comment]
It's actually passed to the `httpLink`. Here's an example :
```
@module "node-fetch" @val
external nodeFetch: ApolloClient.Link.HttpLink.HttpOptions.Js_.t_fetch =
  "default"

let httpLink = () => {
  ApolloClient.Link.HttpLink.make(
    ~credentials="include",
    ~fetch=nodeFetch,
    ~uri=_ => graphqlEndpoint,
    (),
  )
}

let make = () => {
  ApolloClient.make(
      ~link=httpLink(),
      (),
    )
  )
}
```

**Comment by Pet3ris** [comment]
@jeddeloh aah, that makes so much sense! Thank you!
