### ISSUE TITLE
ReScript Apollo Client?

### ISSUE THREAD

**Issue by jeddeloh** [reasonml-community/rescript-apollo-client#58]
Should we get `reason-apollo-client` to stable and then switch to `res-apollo-client`?

**Comment by jfrolich** [comment]
Is res the preferred prefix or rescript? Anyway I agree we should probably switch.

**Comment by jeddeloh** [comment]
I personally like `rescript-` but seems like the momentum is for `res-` and not like I care that much: https://forum.rescript-lang.org/t/libraries-naming-convention/298

**Comment by jfrolich** [comment]
Ah ok! Sounds like it is `res-` indeed!

**Comment by jfrolich** [comment]
https://forum.rescript-lang.org/t/naming-standard-for-new-binding-projects/572/5 🤨

**Comment by jeddeloh** [comment]
😂 Well, maybe it's better that we don't have any convention and people just tag the repository. If we go with `rescript-` it would solve a dilemma I was having of how to refer to the library. Would we still say "ReScript Apollo Client" and the package was `res-apollo-client`? Or would we now just always refer to it as `res-apollo-client`?

**Comment by kgoggin** [comment]
I like `rescript` for the reason you mentioned above. To me, it doesn't make much sense to shorten the package name itself because you hardly ever type it - there's not much need for an abbreviation IMO. And then the package name === what you actually call it.

**Comment by shinzui** [comment]
Would `rescript-apollo-client` compatible with Reason people who don't want to switch to Rescript?

**Comment by jfrolich** [comment]
Yes, it's always compatible as it runs on the same AST.

**Comment by jeddeloh** [comment]
We're now fully transitioned to `rescript-apollo-client`
