### ISSUE TITLE
Convert `@module("@apollo/client/utilities")` into `@module("@apollo/client") @scope("utilites")`

### ISSUE THREAD

**Issue by JasoonS** [reasonml-community/rescript-apollo-client#82]
I was trying this library with vite (but I guess it would be similar with other 'no-bundlers' like snowpack), and it was erroring on this:

![image](https://user-images.githubusercontent.com/6032276/105020058-7f531680-5a4f-11eb-979f-bfe9d1078889.png)
 
I haven't tested the suggestion in the title, but it should work fine and solve these issues with vite.

**Comment by jeddeloh** [comment]
1. I've only ever seen `@scope` documented for binding to globals (though I've used it this way myself). Are we sure this is intended behavior with `@module` that will continue to operate this way?
2. I can't say my bundler knowledge is up-to-date. Does this have any tradeoffs with other bundlers or situations?

**Comment by jeddeloh** [comment]
I haven't done much more thinking about this besides doing a search of the codebase and there are very few deep imports. I'm sure we can figure out a good approach.

**Comment by JasoonS** [comment]
Sorry, I totally got sidetracked.

I think you are right, the following code doesn't work (so `@scope` won't help):
```javascript
import {utilities} from "@apollo/client"
```

To be honest I'm also not very clued up on bundlers. This error comes directly from [Vite](https://github.com/vitejs/vite), so I guess anyone who wants to use `rescript-apollo-client` with vite (or possibly similar libraries like snowpack maybe?) will need to work this one out.

**Comment by jeddeloh** [comment]
Ok, well, happy to reopen this issue when we know more. Thanks!
