### ISSUE TITLE
Add previousData in ApolloClient.Types.QueryResult

### ISSUE THREAD

**Issue by maarekj** [reasonml-community/rescript-apollo-client#83]
As can been seen in the [documentation of Apollo ](https://www.apollographql.com/docs/react/data/queries/#result), the `previousData` property should be added in `ApolloClient.Types.QueryResult`

**Comment by jeddeloh** [comment]
Thanks for pointing this out. I'd happily accept a PR for this. Otherwise, I'll try to get to it soon. I haven't been through the Apollo Client changelog in a while to see if anything needs adding.

**Comment by maarekj** [comment]
I can try to propose a PR, but it won't be for about 10 days...

**Comment by jeddeloh** [comment]
No problem. I'll probably get to it before then. Thanks!

**Comment by jeddeloh** [comment]
See #86. It ended up as an `option<result<'a, 'e>` unfortunately.
